version: 2.0
subscriptionId: 589c7ae9-223e-45e3-a191-98433e0821a9
resourceGroup: AML-Docker-Images
registry: amlmcr
onboardingNotification: amlmcronboarding
dependencyNotification: amlmcrdepnot

ownership:
  securityGroups:
  - groupName: redmond\trainsdkdevs
    permissions:
      - read
      - write
  - groupName: redmond\ems-devs
    permissions:
      - read
      - write

productFamily:
  name: azureml
  displayName: Azure ML
  shortDescription: Official images for the Azure Machine Learning Service.
  readMe: README.md
  logoUrl: https://mcrflowprodcentralus.blob.core.windows.net/defaultlogo/Microsoft_logo.svg?sp=r&st=2019-01-19T00:10:26Z&se=2033-11-04T07:10:26Z&spr=https&sv=2018-03-28&sig=dRn%2BJsqcKwsVdAMcdkzPAbydqSC%2BzBS9BwJUI9AflR4%3D&sr=b 
  supportLink: https://github.com/Azure/AzureML-Containers/issues
  documentationLink: https://docs.microsoft.com/en-us/azure/machine-learning/service/
  syndications:
  - type: dockerhub
    enabled: True


repos:

  - name: public/azureml/base
    displayName: Azureml Base
    readme: README.azureml-base.md
    description: Azure Machine Learning CPU Base Image
    logoUrl: https://mcrflowprodcentralus.blob.core.windows.net/defaultlogo/Microsoft_logo.svg?sp=r&st=2019-01-19T00:10:26Z&se=2033-11-04T07:10:26Z&spr=https&sv=2018-03-28&sig=dRn%2BJsqcKwsVdAMcdkzPAbydqSC%2BzBS9BwJUI9AflR4%3D&sr=b
    supportLink: https://github.com/Azure/AzureML-Containers/issues
    documentationLink: https://docs.microsoft.com/en-us/azure/machine-learning/service/
    #syndications:
      #- type: dockerhub
        #contentUpdate: true
  
  - name: public/azureml/intelmpi2018.3-ubuntu16.04
    displayName: Azureml Base intelmpi2018.3-ubuntu16.04
    readme: README.azureml-intelmpi2018.3-ubuntu16.04.md
    description: Azure Machine Learning CPU Base Image
    logoUrl: https://mcrflowprodcentralus.blob.core.windows.net/defaultlogo/Microsoft_logo.svg?sp=r&st=2019-01-19T00:10:26Z&se=2033-11-04T07:10:26Z&spr=https&sv=2018-03-28&sig=dRn%2BJsqcKwsVdAMcdkzPAbydqSC%2BzBS9BwJUI9AflR4%3D&sr=b
    supportLink: https://github.com/Azure/AzureML-Containers/issues
    documentationLink: https://docs.microsoft.com/en-us/azure/machine-learning/service/
    #syndications:
      #- type: dockerhub
        #contentUpdate: true

  - name: public/azureml/openmpi3.1.2-ubuntu16.04
    displayName: Azureml Base openmpi3.1.2-ubuntu16.04
    readme: README.azureml-openmpi3.1.2-ubuntu16.04.md
    description: Azure Machine Learning CPU Base Image
    logoUrl: https://mcrflowprodcentralus.blob.core.windows.net/defaultlogo/Microsoft_logo.svg?sp=r&st=2019-01-19T00:10:26Z&se=2033-11-04T07:10:26Z&spr=https&sv=2018-03-28&sig=dRn%2BJsqcKwsVdAMcdkzPAbydqSC%2BzBS9BwJUI9AflR4%3D&sr=b
    supportLink: https://github.com/Azure/AzureML-Containers/issues
    documentationLink: https://docs.microsoft.com/en-us/azure/machine-learning/service/
    #syndications:
      #- type: dockerhub
        #contentUpdate: true

  - name: public/azureml/openmpi3.1.2-ubuntu18.04
    displayName: Azureml Base openmpi3.1.2-ubuntu18.04
    readme: README.azureml-openmpi3.1.2-ubuntu18.04.md
    description: Azure Machine Learning CPU Base Image
    logoUrl: https://mcrflowprodcentralus.blob.core.windows.net/defaultlogo/Microsoft_logo.svg?sp=r&st=2019-01-19T00:10:26Z&se=2033-11-04T07:10:26Z&spr=https&sv=2018-03-28&sig=dRn%2BJsqcKwsVdAMcdkzPAbydqSC%2BzBS9BwJUI9AflR4%3D&sr=b
    supportLink: https://github.com/Azure/AzureML-Containers/issues
    documentationLink: https://docs.microsoft.com/en-us/azure/machine-learning/service/
    syndications:
      - type: cloud
        destinations:
          - usnat
          - ussec
        tags:
          - source: latest
          - source: /^\d{8}\.v\d+$/
    
  - name: public/azureml/openmpi4.1.0-ubuntu20.04
    displayName: Azureml Base openmpi4.1.0-ubuntu20.04
    readme: README.azureml-openmpi4.1.0-ubuntu20.04.md
    description: Azure Machine Learning CPU Base Image
    logoUrl: https://mcrflowprodcentralus.blob.core.windows.net/defaultlogo/Microsoft_logo.svg?sp=r&st=2019-01-19T00:10:26Z&se=2033-11-04T07:10:26Z&spr=https&sv=2018-03-28&sig=dRn%2BJsqcKwsVdAMcdkzPAbydqSC%2BzBS9BwJUI9AflR4%3D&sr=b
    supportLink: https://github.com/Azure/AzureML-Containers/issues
    documentationLink: https://docs.microsoft.com/en-us/azure/machine-learning/service/
    syndications:
      - type: cloud
        destinations:
          - usnat
          - ussec
        tags:
          - source: latest
          - source: /^\d{8}\.v\d+$/
    
  - name: public/azureml/base-gpu
    displayName: Azureml Base Gpu
    readme: README.azureml-base-gpu.md
    description: Azure Machine Learning GPU Base Image
    logoUrl: https://mcrflowprodcentralus.blob.core.windows.net/defaultlogo/Microsoft_logo.svg?sp=r&st=2019-01-19T00:10:26Z&se=2033-11-04T07:10:26Z&spr=https&sv=2018-03-28&sig=dRn%2BJsqcKwsVdAMcdkzPAbydqSC%2BzBS9BwJUI9AflR4%3D&sr=b
    supportLink: https://github.com/Azure/AzureML-Containers/issues
    documentationLink: https://docs.microsoft.com/en-us/azure/machine-learning/service/ 
    #syndications:
     # - type: dockerhub
        #contentUpdate: true

  - name: public/azureml/intelmpi2018.3-cuda9.0-cudnn7-ubuntu16.04
    displayName: Azureml Base Gpu intelmpi2018.3-cuda9.0-cudnn7-ubuntu16.04
    readme: README.azureml-intelmpi2018.3-cuda9.0-cudnn7-ubuntu16.04.md
    description: Azure Machine Learning GPU Base Image
    logoUrl: https://mcrflowprodcentralus.blob.core.windows.net/defaultlogo/Microsoft_logo.svg?sp=r&st=2019-01-19T00:10:26Z&se=2033-11-04T07:10:26Z&spr=https&sv=2018-03-28&sig=dRn%2BJsqcKwsVdAMcdkzPAbydqSC%2BzBS9BwJUI9AflR4%3D&sr=b
    supportLink: https://github.com/Azure/AzureML-Containers/issues
    documentationLink: https://docs.microsoft.com/en-us/azure/machine-learning/service/ 
    #syndications:
      #- type: dockerhub
        #contentUpdate: true

  - name: public/azureml/intelmpi2018.3-cuda10.0-cudnn7-ubuntu16.04
    displayName: Azureml Base Gpu intelmpi2018.3-cuda10.0-cudnn7-ubuntu16.04
    readme: README.azureml-intelmpi2018.3-cuda10.0-cudnn7-ubuntu16.04.md
    description: Azure Machine Learning GPU Base Image
    logoUrl: https://mcrflowprodcentralus.blob.core.windows.net/defaultlogo/Microsoft_logo.svg?sp=r&st=2019-01-19T00:10:26Z&se=2033-11-04T07:10:26Z&spr=https&sv=2018-03-28&sig=dRn%2BJsqcKwsVdAMcdkzPAbydqSC%2BzBS9BwJUI9AflR4%3D&sr=b
    supportLink: https://github.com/Azure/AzureML-Containers/issues
    documentationLink: https://docs.microsoft.com/en-us/azure/machine-learning/service/ 
    #syndications:
      #- type: dockerhub
        #contentUpdate: true

  - name: public/azureml/openmpi3.1.2-cuda9.0-cudnn7-ubuntu16.04
    displayName: Azureml Base Gpu openmpi3.1.2-cuda9.0-cudnn7-ubuntu16.04
    readme: README.azureml-openmpi3.1.2-cuda9.0-cudnn7-ubuntu16.04.md
    description: Azure Machine Learning GPU Base Image
    logoUrl: https://mcrflowprodcentralus.blob.core.windows.net/defaultlogo/Microsoft_logo.svg?sp=r&st=2019-01-19T00:10:26Z&se=2033-11-04T07:10:26Z&spr=https&sv=2018-03-28&sig=dRn%2BJsqcKwsVdAMcdkzPAbydqSC%2BzBS9BwJUI9AflR4%3D&sr=b
    supportLink: https://github.com/Azure/AzureML-Containers/issues
    documentationLink: https://docs.microsoft.com/en-us/azure/machine-learning/service/ 
    #syndications:
      #- type: dockerhub
        #contentUpdate: true

  - name: public/azureml/openmpi3.1.2-cuda10.0-cudnn7-ubuntu16.04
    displayName: Azureml Base Gpu openmpi3.1.2-cuda10.0-cudnn7-ubuntu16.04
    readme: README.azureml-openmpi3.1.2-cuda10.0-cudnn7-ubuntu16.04.md
    description: Azure Machine Learning GPU Base Image
    logoUrl: https://mcrflowprodcentralus.blob.core.windows.net/defaultlogo/Microsoft_logo.svg?sp=r&st=2019-01-19T00:10:26Z&se=2033-11-04T07:10:26Z&spr=https&sv=2018-03-28&sig=dRn%2BJsqcKwsVdAMcdkzPAbydqSC%2BzBS9BwJUI9AflR4%3D&sr=b
    supportLink: https://github.com/Azure/AzureML-Containers/issues
    documentationLink: https://docs.microsoft.com/en-us/azure/machine-learning/service/ 
    #syndications:
      #- type: dockerhub
        #contentUpdate: true

  - name: public/azureml/openmpi3.1.2-cuda10.0-cudnn7-ubuntu18.04
    displayName: Azureml Base Gpu openmpi3.1.2-cuda10.0-cudnn7-ubuntu18.04
    readme: README.azureml-openmpi3.1.2-cuda10.0-cudnn7-ubuntu18.04.md
    description: Azure Machine Learning GPU Base Image
    logoUrl: https://mcrflowprodcentralus.blob.core.windows.net/defaultlogo/Microsoft_logo.svg?sp=r&st=2019-01-19T00:10:26Z&se=2033-11-04T07:10:26Z&spr=https&sv=2018-03-28&sig=dRn%2BJsqcKwsVdAMcdkzPAbydqSC%2BzBS9BwJUI9AflR4%3D&sr=b
    supportLink: https://github.com/Azure/AzureML-Containers/issues
    documentationLink: https://docs.microsoft.com/en-us/azure/machine-learning/service/ 
    syndications:
      - type: cloud
        destinations:
          - usnat
          - ussec
        tags:
          - source: latest
          - source: /^\d{8}\.v\d+$/

  - name: public/azureml/openmpi3.1.2-cuda10.1-cudnn7-ubuntu18.04
    displayName: Azureml Base Gpu openmpi3.1.2-cuda10.1-cudnn7-ubuntu18.04
    readme: README.azureml-openmpi3.1.2-cuda10.1-cudnn7-ubuntu18.04.md
    description: Azure Machine Learning GPU Base Image
    logoUrl: https://mcrflowprodcentralus.blob.core.windows.net/defaultlogo/Microsoft_logo.svg?sp=r&st=2019-01-19T00:10:26Z&se=2033-11-04T07:10:26Z&spr=https&sv=2018-03-28&sig=dRn%2BJsqcKwsVdAMcdkzPAbydqSC%2BzBS9BwJUI9AflR4%3D&sr=b
    supportLink: https://github.com/Azure/AzureML-Containers/issues
    documentationLink: https://docs.microsoft.com/en-us/azure/machine-learning/service/ 
    syndications:
      - type: cloud
        destinations:
          - usnat
          - ussec
        tags:
          - source: latest
          - source: /^\d{8}\.v\d+$/
        
  - name: public/azureml/openmpi3.1.2-cuda10.2-cudnn7-ubuntu18.04
    displayName: Azureml Base Gpu openmpi3.1.2-cuda10.2-cudnn7-ubuntu18.04
    readme: README.azureml-openmpi3.1.2-cuda10.2-cudnn7-ubuntu18.04.md
    description: Azure Machine Learning GPU Base Image
    logoUrl: https://mcrflowprodcentralus.blob.core.windows.net/defaultlogo/Microsoft_logo.svg?sp=r&st=2019-01-19T00:10:26Z&se=2033-11-04T07:10:26Z&spr=https&sv=2018-03-28&sig=dRn%2BJsqcKwsVdAMcdkzPAbydqSC%2BzBS9BwJUI9AflR4%3D&sr=b
    supportLink: https://github.com/Azure/AzureML-Containers/issues
    documentationLink: https://docs.microsoft.com/en-us/azure/machine-learning/service/ 
    syndications:
      - type: cloud
        destinations:
          - usnat
          - ussec
        tags:
          - source: latest
          - source: /^\d{8}\.v\d+$/

  - name: public/azureml/openmpi3.1.2-cuda10.2-cudnn8-ubuntu18.04
    displayName: Azureml Base Gpu openmpi3.1.2-cuda10.2-cudnn8-ubuntu18.04
    readme: README.azureml-openmpi3.1.2-cuda10.2-cudnn8-ubuntu18.04.md
    description: Azure Machine Learning GPU Base Image
    logoUrl: https://mcrflowprodcentralus.blob.core.windows.net/defaultlogo/Microsoft_logo.svg?sp=r&st=2019-01-19T00:10:26Z&se=2033-11-04T07:10:26Z&spr=https&sv=2018-03-28&sig=dRn%2BJsqcKwsVdAMcdkzPAbydqSC%2BzBS9BwJUI9AflR4%3D&sr=b
    supportLink: https://github.com/Azure/AzureML-Containers/issues
    documentationLink: https://docs.microsoft.com/en-us/azure/machine-learning/service/
    syndications:
      - type: cloud
        destinations:
          - usnat
          - ussec
        tags:
          - source: latest
          - source: /^\d{8}\.v\d+$/
        
  - name: public/azureml/eyes-off-gpu
    displayName: Azureml eyes-off-gpu
    description: Azure Machine Learning GPU Base Image
    logoUrl: https://mcrflowprodcentralus.blob.core.windows.net/defaultlogo/Microsoft_logo.svg?sp=r&st=2019-01-19T00:10:26Z&se=2033-11-04T07:10:26Z&spr=https&sv=2018-03-28&sig=dRn%2BJsqcKwsVdAMcdkzPAbydqSC%2BzBS9BwJUI9AflR4%3D&sr=b
    supportLink: https://github.com/Azure/AzureML-Containers/issues
    documentationLink: https://docs.microsoft.com/en-us/azure/machine-learning/service/
    
  - name: public/azureml/openmpi4.1.0-cuda11.0.3-cudnn8-ubuntu18.04
    displayName: Azureml Base Gpu openmpi4.1.0-cuda11.0.3-cudnn8-ubuntu18.04
    readme: README.azureml-openmpi4.1.0-cuda11.0.3-cudnn8-ubuntu18.04.md
    description: Azure Machine Learning GPU Base Image
    logoUrl: https://mcrflowprodcentralus.blob.core.windows.net/defaultlogo/Microsoft_logo.svg?sp=r&st=2019-01-19T00:10:26Z&se=2033-11-04T07:10:26Z&spr=https&sv=2018-03-28&sig=dRn%2BJsqcKwsVdAMcdkzPAbydqSC%2BzBS9BwJUI9AflR4%3D&sr=b
    supportLink: https://github.com/Azure/AzureML-Containers/issues
    documentationLink: https://docs.microsoft.com/en-us/azure/machine-learning/service/
    syndications:
      - type: cloud
        destinations:
          - usnat
          - ussec
        tags:
          - source: latest
          - source: /^\d{8}\.v\d+$/
    
  - name: public/azureml/openmpi4.1.0-cuda11.1-cudnn8-ubuntu18.04
    displayName: Azureml Base Gpu openmpi4.1.0-cuda11.1-cudnn8-ubuntu18.04
    readme: README.azureml-openmpi4.1.0-cuda11.1-cudnn8-ubuntu18.04.md
    description: Azure Machine Learning GPU Base Image
    logoUrl: https://mcrflowprodcentralus.blob.core.windows.net/defaultlogo/Microsoft_logo.svg?sp=r&st=2019-01-19T00:10:26Z&se=2033-11-04T07:10:26Z&spr=https&sv=2018-03-28&sig=dRn%2BJsqcKwsVdAMcdkzPAbydqSC%2BzBS9BwJUI9AflR4%3D&sr=b
    supportLink: https://github.com/Azure/AzureML-Containers/issues
    documentationLink: https://docs.microsoft.com/en-us/azure/machine-learning/service/
    syndications:
      - type: cloud
        destinations:
          - usnat
          - ussec
        tags:
          - source: latest
          - source: /^\d{8}\.v\d+$/
    
  - name: public/azureml/openmpi4.1.0-cuda11.1-cudnn8-ubuntu20.04
    displayName: Azureml Base Gpu openmpi4.1.0-cuda11.1-cudnn8-ubuntu20.04
    readme: README.azureml-openmpi4.1.0-cuda11.1-cudnn8-ubuntu20.04.md
    description: Azure Machine Learning GPU Base Image
    logoUrl: https://mcrflowprodcentralus.blob.core.windows.net/defaultlogo/Microsoft_logo.svg?sp=r&st=2019-01-19T00:10:26Z&se=2033-11-04T07:10:26Z&spr=https&sv=2018-03-28&sig=dRn%2BJsqcKwsVdAMcdkzPAbydqSC%2BzBS9BwJUI9AflR4%3D&sr=b
    supportLink: https://github.com/Azure/AzureML-Containers/issues
    documentationLink: https://docs.microsoft.com/en-us/azure/machine-learning/service/
    syndications:
      - type: cloud
        destinations:
          - usnat
          - ussec
        tags:
          - source: latest
          - source: /^\d{8}\.v\d+$/
    
  - name: public/azureml/aml-triton
    displayName: Azureml Base Triton aml-triton
    readme: README.azureml-base-triton.md
    description: Azure Machine Learning Triton Base Image
    logoUrl: https://mcrflowprodcentralus.blob.core.windows.net/defaultlogo/Microsoft_logo.svg?sp=r&st=2019-01-19T00:10:26Z&se=2033-11-04T07:10:26Z&spr=https&sv=2018-03-28&sig=dRn%2BJsqcKwsVdAMcdkzPAbydqSC%2BzBS9BwJUI9AflR4%3D&sr=b
    supportLink: https://github.com/Azure/AzureML-Containers/issues
    documentationLink: https://docs.microsoft.com/en-us/azure/machine-learning/service/
    syndications:
      - type: dockerhub
        contentUpdate: true

  - name: public/azureml/base-lite
    displayName: Azureml Base Lite ubuntu16.04
    readme: README.azureml-base-lite.md
    description: Azure Machine Learning Lite Base Image
    logoUrl: https://mcrflowprodcentralus.blob.core.windows.net/defaultlogo/Microsoft_logo.svg?sp=r&st=2019-01-19T00:10:26Z&se=2033-11-04T07:10:26Z&spr=https&sv=2018-03-28&sig=dRn%2BJsqcKwsVdAMcdkzPAbydqSC%2BzBS9BwJUI9AflR4%3D&sr=b
    supportLink: https://github.com/Azure/AzureML-Containers/issues
    documentationLink: https://docs.microsoft.com/en-us/azure/machine-learning/service/ 

  - name: public/azureml/ubuntu16.04
    displayName: Azureml Base Lite
    readme: README.azureml-base-lite.md
    description: Azure Machine Learning Lite Base Image
    logoUrl: https://mcrflowprodcentralus.blob.core.windows.net/defaultlogo/Microsoft_logo.svg?sp=r&st=2019-01-19T00:10:26Z&se=2033-11-04T07:10:26Z&spr=https&sv=2018-03-28&sig=dRn%2BJsqcKwsVdAMcdkzPAbydqSC%2BzBS9BwJUI9AflR4%3D&sr=b
    supportLink: https://github.com/Azure/AzureML-Containers/issues
    documentationLink: https://docs.microsoft.com/en-us/azure/machine-learning/service/ 

  - name: public/azureml/r-base
    displayName: Azureml R Base
    readme: README.azureml-r-base.md
    description: Azure Machine Learning R Base Image
    logoUrl: https://mcrflowprodcentralus.blob.core.windows.net/defaultlogo/Microsoft_logo.svg?sp=r&st=2019-01-19T00:10:26Z&se=2033-11-04T07:10:26Z&spr=https&sv=2018-03-28&sig=dRn%2BJsqcKwsVdAMcdkzPAbydqSC%2BzBS9BwJUI9AflR4%3D&sr=b
    supportLink: https://github.com/Azure/AzureML-Containers/issues
    documentationLink: https://docs.microsoft.com/en-us/azure/machine-learning/service/
    syndications:
      - type: dockerhub
        contentUpdate: true
    
  - name: public/azureml/3.5dotnet-ltsc2019
    displayName: Azureml Base Windows 3.5dotnet-ltsc2019
    description: Azure Machine Learning Windows ServerCore Image
    logoUrl: https://mcrflowprodcentralus.blob.core.windows.net/defaultlogo/Microsoft_logo.svg?sp=r&st=2019-01-19T00:10:26Z&se=2033-11-04T07:10:26Z&spr=https&sv=2018-03-28&sig=dRn%2BJsqcKwsVdAMcdkzPAbydqSC%2BzBS9BwJUI9AflR4%3D&sr=b
    supportLink: https://github.com/Azure/AzureML-Containers/issues
    documentationLink: https://docs.microsoft.com/en-us/azure/machine-learning/service/

  - name: public/azureml/windows-1809
    displayName: Azureml Base Windows windows-1809
    description: Azure Machine Learning Windows Full Image
    logoUrl: https://mcrflowprodcentralus.blob.core.windows.net/defaultlogo/Microsoft_logo.svg?sp=r&st=2019-01-19T00:10:26Z&se=2033-11-04T07:10:26Z&spr=https&sv=2018-03-28&sig=dRn%2BJsqcKwsVdAMcdkzPAbydqSC%2BzBS9BwJUI9AflR4%3D&sr=b
    supportLink: https://github.com/Azure/AzureML-Containers/issues
    documentationLink: https://docs.microsoft.com/en-us/azure/machine-learning/service/
    
  - name: public/azureml/windows-servercore-1809
    displayName: Azureml Base Windows windows-servercore-1809
    description: Azure Machine Learning Windows Server Core Image
    logoUrl: https://mcrflowprodcentralus.blob.core.windows.net/defaultlogo/Microsoft_logo.svg?sp=r&st=2019-01-19T00:10:26Z&se=2033-11-04T07:10:26Z&spr=https&sv=2018-03-28&sig=dRn%2BJsqcKwsVdAMcdkzPAbydqSC%2BzBS9BwJUI9AflR4%3D&sr=b
    supportLink: https://github.com/Azure/AzureML-Containers/issues
    documentationLink: https://docs.microsoft.com/en-us/azure/machine-learning/service/
    
  - name: public/azureml/windows-2004
    displayName: Azureml Base Windows windows-2004
    description: Azure Machine Learning Windows Full Image
    logoUrl: https://mcrflowprodcentralus.blob.core.windows.net/defaultlogo/Microsoft_logo.svg?sp=r&st=2019-01-19T00:10:26Z&se=2033-11-04T07:10:26Z&spr=https&sv=2018-03-28&sig=dRn%2BJsqcKwsVdAMcdkzPAbydqSC%2BzBS9BwJUI9AflR4%3D&sr=b
    supportLink: https://github.com/Azure/AzureML-Containers/issues
    documentationLink: https://docs.microsoft.com/en-us/azure/machine-learning/service/
